ruby-practice/tuesday/games_on_rails/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get 'magic_ball' => 'magic_ball#result'

  get 'guess_secret_number' => 'secret_number#guess'

  post 'secret_number_results/:guess' => 'secret_number#result', :as => 'secret_number_results'

  get 'play_rps' => 'rps#play'
  post 'rps_result/:weapon' => 'rps#result', :as => "rps_result"

end

ruby-practice/tuesday/games_on_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby-practice/tuesday/games_on_rails/app/controllers/magic_ball_controller.rb
class MagicBallController < ApplicationController

  def result
    @magic_answer = generate_random_response  # the @ symbol is an instance variable
    puts @magic_answer
  end

  private
  def generate_random_response
    all_responses =
      ["Thou shall not pass",
      "I guess so",
      "Maybe. Just maybe",
      "WTH",
      "What is up"]
      all_responses.sample
  end

end

ruby-practice/tuesday/games_on_rails/app/controllers/rps_controller.rb
class RpsController < ApplicationController
  def play
  end

  def result
    @user_weapon = params[:weapon]
    @server_weapon = generate_server_weapon
    @result = generate_results(@user_weapon, @server_weapon)
  end

  private
  def generate_server_weapon
    ["rock", "paper", "scissors"].sample
  end

  def generate_results(user_weapon, server_weapon)
    # Your logic for determining results
    if user_weapon == server_weapon
      return "Draw"
    end

    winner_of = {
      "rock" => "paper",
      "paper" => "scissors",
      "scissors" => "rock"
    }

    if winner_of[server_weapon] == user_weapon
      return "Win"
    else
      return "Lose"
    end

  end
end

ruby-practice/tuesday/games_on_rails/app/controllers/secret_number_controller.rb
class SecretNumberController < ApplicationController
  def guess
    # Rails will look into a folder in "views/secret_number"
    # to look for an ERB file named 'guess.html.erb'.
    # This erb file will tell Rails what HTML to render
  end

  def result
    # Rails will look into a folder in "views/secret_number" (because the controller is named secret_number)
    # to look for an ERB file named 'result.html.erb'.
    # This erb file will tell Rails what HTML to render 

    @result = params[:guess].to_i == generate_secret_number
  end

  private
  def generate_secret_number
    4
  end
end

ruby-practice/tuesday/games_on_rails/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    
  end
end

ruby-practice/tuesday/games_on_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby-practice/tuesday/games_on_rails/app/views/games/rock_paper_scissors_play.html.erb
<p>
  You asked: <%= params[:question] || "Nothing" %>
</p>

<%= form_tag('/magic_ball', method: :get) do %>
  <%= text_field_tag :question, nil, { placeholder: "Enter your question", class: "question_class" } %>
  <%= submit_tag "Ask" %>
<% end %>

<% if params[:question].present? %>
  <%= image_tag "magic_ball.jpg" %>
  <h1>The Magic 8 Ball says...</h1>
  <p>
    <%= @magic_answer %>
  </p>
<% end %>

ruby-practice/tuesday/games_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GamesOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ruby-practice/tuesday/games_on_rails/app/views/magic_ball/result.html.erb
<p>
  You asked: <%= params[:question] || "Nothing" %>
</p>

<%= form_tag('/magic_ball', method: :get) do %>
  <%= text_field_tag :question, nil, { placeholder: "Enter your question", class: "question_class" } %>
  <%= submit_tag "Ask" %>
<% end %>

<% if params[:question].present? %>
  <%= image_tag "magic_ball.jpg" %>
  <h1>The Magic 8 Ball says...</h1>
  <p>
    <%= @magic_answer %>
  </p>
<% end %>

ruby-practice/tuesday/games_on_rails/app/views/rps/play.html.erb
<p>Choose your move:</p>

<%= link_to "Rock", rps_result_path(:weapon => "rock"), method: :post %>
<%= link_to "Paper", rps_result_path(:weapon => "paper"), method: :post %>
<%= link_to "Scissors", rps_result_path(:weapon => "scissors"), method: :post %>

ruby-practice/tuesday/games_on_rails/app/views/rps/result.html.erb
<h1>Results</h1>
<p><%= @result %></p>
<!-- Show results here and what server/user chose -->

<p>You showed a <%= @user_weapon %></p>
<p>The computer chose <%= @server_weapon %></p>

<%= link_to "Try Again", play_rps_path %>

ruby-practice/tuesday/games_on_rails/app/views/secret_number/guess.html.erb
<h1>My guess is: </h1>

<% 11.times do |i| %>
  <%= link_to "Guess #{i}", secret_number_results_path(guess: i), method: :post %>
<% end %>

<!-- The path helper (i.e., adding _path after the secret_number_results)
and the 'post' option changes the url hash to
http://localhost:3000/secret_number_results/4  when clicked.
Because the post method was invoked, Rails will then look at routes.rb,
and see "  post 'secret_number_results/:guess' => 'secret_number#result', :as => 'secret_number_results'"
This in turn makes Rails look into the secret_number controlled and execute the function called 'result'.
 -->

ruby-practice/tuesday/games_on_rails/app/views/secret_number/result.html.erb
<%= @result %>

ruby-practice/tuesday/games_on_rails/app/views/static_pages/index.html.erb
<h1>Hello world</h1>