ruby-practice/tuesday/blogger/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

    resources :posts do
      resources :comments, :only => [:create, :destroy]
    end # resources simply generate the 7 default crud operations

end

ruby-practice/tuesday/blogger/app/models/comment.rb
class Comment < ActiveRecord::Base  #there is an active module called ActiveRecord and inside it we have a class called  base
  belongs_to :post
end

ruby-practice/tuesday/blogger/app/models/post.rb
class Post < ActiveRecord::Base  #there is an active module called ActiveRecord and inside it we have a class called  base
  validates :title, presence: true  # validates that all posts have a title
  has_many :comments
end

ruby-practice/tuesday/blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby-practice/tuesday/blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    # @comment = Comment.new(comment_params)   # the string from comment_params gets fed in as the new comment
    # @comment.post_id = @post.id
    # instead of the two lines above, we can just use "build":
    @comment = @post.comments.build(comment_params)

    if !@comment.save
      flash[:error] = "Comment failed to save"
    end
    redirect_to post_path(@post)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    if !@comment.destroy
      flash[:error] = "Comment failed to delete"
    end
    redirect_to posts_path(:id => @post.id) # or root_path
  end

  private
  def comment_params
    params.require(:comment).permit(:body)  # returns {:body = "a string"}
  end

end

ruby-practice/tuesday/blogger/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params) #post_params is a hash-like object
    if @post.save
      flash[:error] = "" # by right, you don't even need to write this
      redirect_to(post_path(@post.id))
    else # for example if post doesnt have a title
      flash[:error] = "There was a problem trying to create the post! #{@post.errors.full_messages.join(', ')}"
      render :new #the 'new' here refers to the new.html.erb view
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)   # note that post_params simply returns the result of the private function post_params called below
      redirect_to(post_path(@post.id))
    else
      render :edit
      flash[:error] = "There was a problem trying to update the post! #{@post.errors.full_messages.join(', ')}"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path # or root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

ruby-practice/tuesday/blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby-practice/tuesday/blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="error-messages">
    <% if flash[:error].present? %>
      <%= flash[:error] %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

ruby-practice/tuesday/blogger/app/views/posts/edit.html.erb
<h3>Edit Post</h3>

<%= form_for @post, url: post_path, method: :put do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

ruby-practice/tuesday/blogger/app/views/posts/index.html.erb
<h1>Welcome to my blog!</h1>

<%= link_to "New Post", new_post_path %>
<br>

<% @posts.each do |post| %>
  <h3><%= post.title %></h3>
  <p><%= post.body %></p>

  <%= link_to "See more", post_path(post.id) %>
<% end %>

ruby-practice/tuesday/blogger/app/views/posts/new.html.erb
<h3>New Post</h3>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

ruby-practice/tuesday/blogger/app/views/posts/show.html.erb
<h3><%= @post.title %></h3>
<p><%= @post.body %></p>

<%= link_to "Back to all posts", posts_path %>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete %>

<hr>

<% @post.comments.each do |comment| %>
  <div class="comment">
    <%= "> " + comment.body %>
    <%= link_to "Delete", post_comment_path(:post_id => @post.id, :id => comment.id), :method => :delete %>
    <%# <%= link_to "Delete", post_comment(@post, comment), :method => :delete %>
  </div>
<% end %>

<%= form_for Comment.new, :url => post_comments_path(:post_id => @post.id) do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit "Create New Comment" %>
<% end %>